import sys
import os as osmod

# This is a comment

dct = {
    "a": "b"
}

lst = [
    "a",
    "b"
]

tup = (
    "a",
    "b"
)

x = 5 + \
    4

env.ENV_NAME = 'foobar'
if $([[ "env.ENV_NAME" =~ ^([a-zA-Z0-9]|-)*$ ]]) == 0:
    print("success")

def search():
    env.SEARCH_PATH = sys.argv[1]
    env.SEARCH_TERM = sys.argv[2]
    echo "Searching in env.SEARCH_PATH"
    echo "Searching for env.SEARCH_TERM"
    print($?)
    osmod.getcwd()

    if $(cat "env.SEARCH_PATH" | grep -q "env.SEARCH_TERM") == 0:
        print('search string found')
    else:
        print('Could not find search string')

    env.FOO = $(echo "bar")

search()
