name: CI
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.13]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov black
      - name: Install Calligraphy
        run: |
          pip install .
      - name: Lint code
        run: |
          pylint calligraphy_scripting
      - name: Run tests
        run: |
          pytest --cov=calligraphy_scripting --cov-report=xml --cov-fail-under=95 -W ignore::DeprecationWarning
      - name: Get coverage
        run: |
          WHOLE=$(cat coverage.xml | grep "name=\".\"" | awk '{print $3}' | cut -c14-15)
          DECIMAL=$(cat coverage.xml | grep "name=\".\"" | awk '{print $3}' | cut -c16-17)
          echo "COVERAGE=$(echo \"${WHOLE}.${DECIMAL}%\")" >> $GITHUB_ENV

          REF=${{ github.ref }}
          echo "github.ref: $REF"
          IFS='/' read -ra PATHS <<< "$REF"
          BRANCH_NAME="${PATHS[1]}_${PATHS[2]}"
          echo $BRANCH_NAME
          echo "BRANCH=$(echo ${BRANCH_NAME})" >> $GITHUB_ENV
      - name: Create Coverage Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 7d4c25ef2e97e8de523ef7c1fee26e8e
          filename: your-repo-name__${{ env.BRANCH }}.json
          label: Test Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: pytest
      # - name: Coverage Badge
      #   uses: tj-actions/coverage-badge-py@v1.2
      # - name: Verify Changed files
      #   uses: tj-actions/verify-changed-files@v6
      #   id: changed_files
      #   with:
      #     files: img/coverage.svg
      # - name: Commit files
      #   if: steps.changed_files.outputs.files_changed == 'true'
      #   run: |
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add img/coverage.svg
      #     git commit -m "DOC: Updated coverage.svg"
      # - name: Push changes
      #   if: steps.changed_files.outputs.files_changed == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     branch: ${{ github.ref }}
