name: CI
on: pull_request

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.1.13]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pytest pytest-cov black
      - name: Install Calligraphy
        run: |
          pip install .
      - name: Lint code
        run: |
          pylint calligraphy_scripting
      - name: Run tests
        run: |
          pytest --cov=calligraphy_scripting --cov-fail-under=95 -W ignore::DeprecationWarning
      # - name: Coverage Badge
      #   uses: tj-actions/coverage-badge-py@v1.2
      # - name: Verify Changed files
      #   uses: tj-actions/verify-changed-files@v6
      #   id: changed_files
      #   with:
      #     files: img/coverage.svg
      # - name: Commit files
      #   if: steps.changed_files.outputs.files_changed == 'true'
      #   run: |
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add img/coverage.svg
      #     git commit -m "DOC: Updated coverage.svg"
      # - name: Push changes
      #   if: steps.changed_files.outputs.files_changed == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.github_token }}
      #     branch: ${{ github.ref }}
